version: '2'
services:
  app:
    build: .
    volumes:
      - .:/go/src/app
    ports:
      - "18888:18888"
      - "18443:18443"
    command: bash -c "dep ensure && go run http.go && go run https.go"
