version: '2'
services:
  http1:
    build: http1/.
    volumes:
      - ./http1/.:/go/src/app
    ports:
      - "18888:18888"
    privileged: true
    command: bash -c "(dep init || dep ensure) && go run http.go"
  http1.1:
    build: http1.1/.
    volumes:
      - ./http1.1/.:/go/src/app
    ports:
      - "18443:18443"
    privileged: true
    command: bash -c "(dep init || dep ensure) && go run https.go"
  webserver:
    image: nginx
    ports:
      - "80:80"
  proxyserver:
    image: poklet/squid
    ports:
      - "3128:3128"
