version: '2'
services:
  webserver:
    image: nginx
    ports:
      - "80:80"

  proxyserver:
    image: poklet/squid
    ports:
      - "3128:3128"

  http1:
    build: http1/.
    volumes:
      - ./http1/.:/go/src/app
    ports:
      - "18888:18888"
    privileged: true
    command: bash build.sh

  http1.1_server_certs:
    build: http1.1_server_certs/.
    volumes:
      - ./http1.1_server_certs/.:/go/src/app
    ports:
      - "18443:18443"
    privileged: true
    command: bash build.sh

  http1.1_server_and_client_certs:
    build: http1.1_server_and_client_certs/.
    volumes:
      - ./http1.1_server_and_client_certs/.:/go/src/app
    ports:
      - "18442:18442"
    privileged: true
    command: bash build.sh

  http1.1_protocol_upgrade:
    build: http1.1_protocol_upgrade/.
    volumes:
      - ./http1.1_protocol_upgrade/.:/go/src/app
    ports:
      - "18887:18887"
    privileged: true
    command: bash build.sh


  http1.1_chunk:
    build: http1.1_chunk/.
    volumes:
      - ./http1.1_chunk/.:/go/src/app
    ports:
      - "18886:18886"
    privileged: true
    command: bash build.sh

  http1.1_rpc:
    build: http1.1_rpc/.
    volumes:
      - ./http1.1_rpc/.:/go/src/app
    ports:
      - "18885:18885"
    privileged: true
    command: bash build.sh

  http2_server_sent_events:
    build: http2_server_sent_events/.
    volumes:
      - ./http2_server_sent_events/.:/go/src/app
    ports:
      - "18884:18884"
    privileged: true
    command: bash build.sh

  http2_websocket:
    build: http2_websocket/.
    volumes:
      - ./http2_websocket/.:/go/src/app
    ports:
      - "18883:18883"
    privileged: true
    command: bash build.sh
