version: '2'
services:
  app:
    build: .
    volumes:
      - .:/go/src/app
    ports:
      - "18888:18888"
      - "18443:18443"
    network_mode: "host"
    command: bash -c "dep ensure && go run http1/server.go && go run http1.1_client/https_server.go"
